package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Bm;
import pojo.BmExample;

public interface BmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    long countByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int deleteByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int insert(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int insertSelective(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    List<Bm> selectByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    Bm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Bm record, @Param("example") BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int updateByExample(@Param("record") Bm record, @Param("example") BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int updateByPrimaryKeySelective(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Mon Dec 13 15:16:08 CST 2021
     */
    int updateByPrimaryKey(Bm record);
}